/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcademiesRouteImport } from './routes/academies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersIdRouteImport } from './routes/players.$id'
import { Route as ApiPublicHooksInactivityCheckRouteImport } from './routes/api/public/hooks/inactivity-check'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiesRoute = AcademiesRouteImport.update({
  id: '/academies',
  path: '/academies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIdRoute = PlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksInactivityCheckRoute =
  ApiPublicHooksInactivityCheckRouteImport.update({
    id: '/api/public/hooks/inactivity-check',
    path: '/api/public/hooks/inactivity-check',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academies': typeof AcademiesRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/rankings': typeof RankingsRoute
  '/security': typeof SecurityRoute
  '/videos': typeof VideosRoute
  '/players/$id': typeof PlayersIdRoute
  '/api/public/hooks/inactivity-check': typeof ApiPublicHooksInactivityCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academies': typeof AcademiesRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/rankings': typeof RankingsRoute
  '/security': typeof SecurityRoute
  '/videos': typeof VideosRoute
  '/players/$id': typeof PlayersIdRoute
  '/api/public/hooks/inactivity-check': typeof ApiPublicHooksInactivityCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academies': typeof AcademiesRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/rankings': typeof RankingsRoute
  '/security': typeof SecurityRoute
  '/videos': typeof VideosRoute
  '/players/$id': typeof PlayersIdRoute
  '/api/public/hooks/inactivity-check': typeof ApiPublicHooksInactivityCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academies'
    | '/auth'
    | '/dashboard'
    | '/discover'
    | '/messages'
    | '/privacy'
    | '/rankings'
    | '/security'
    | '/videos'
    | '/players/$id'
    | '/api/public/hooks/inactivity-check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academies'
    | '/auth'
    | '/dashboard'
    | '/discover'
    | '/messages'
    | '/privacy'
    | '/rankings'
    | '/security'
    | '/videos'
    | '/players/$id'
    | '/api/public/hooks/inactivity-check'
  id:
    | '__root__'
    | '/'
    | '/academies'
    | '/auth'
    | '/dashboard'
    | '/discover'
    | '/messages'
    | '/privacy'
    | '/rankings'
    | '/security'
    | '/videos'
    | '/players/$id'
    | '/api/public/hooks/inactivity-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademiesRoute: typeof AcademiesRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  MessagesRoute: typeof MessagesRoute
  PrivacyRoute: typeof PrivacyRoute
  RankingsRoute: typeof RankingsRoute
  SecurityRoute: typeof SecurityRoute
  VideosRoute: typeof VideosRoute
  PlayersIdRoute: typeof PlayersIdRoute
  ApiPublicHooksInactivityCheckRoute: typeof ApiPublicHooksInactivityCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academies': {
      id: '/academies'
      path: '/academies'
      fullPath: '/academies'
      preLoaderRoute: typeof AcademiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$id': {
      id: '/players/$id'
      path: '/players/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof PlayersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/inactivity-check': {
      id: '/api/public/hooks/inactivity-check'
      path: '/api/public/hooks/inactivity-check'
      fullPath: '/api/public/hooks/inactivity-check'
      preLoaderRoute: typeof ApiPublicHooksInactivityCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademiesRoute: AcademiesRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  MessagesRoute: MessagesRoute,
  PrivacyRoute: PrivacyRoute,
  RankingsRoute: RankingsRoute,
  SecurityRoute: SecurityRoute,
  VideosRoute: VideosRoute,
  PlayersIdRoute: PlayersIdRoute,
  ApiPublicHooksInactivityCheckRoute: ApiPublicHooksInactivityCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
